---
abstract: "An entry with tooltip in the entry if it's empty"
author:
  - 'Alexander Becker <c a p f a n ^at^ g m x -dot- d e>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.98
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.08
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk-TipEntry
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 6.98
  Test::More: 0.98
  Test::Pod: 1.45
  Tk: 804.029
  perl: 5.012002
resources:
  repository: https://github.com/asb-capfan/Tk-TipEntry
version: 0.03
