---
abstract: "An entry with tooltip in the entry if it's empty"
author:
  - 'Alexander Becker <c a p f a n ^at^ g m x -dot- d e>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk-TipEntry
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0.98
  Test::Pod: 1.45
  Tk: 804.029
version: 0.02
